---
abstract: 'Geo::Hash in XS'
author:
  - 'Daisuke Maki <daisuke@endeworks.jp>'
build_requires:
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.42
  ExtUtils::ParseXS: 2.21
  Test::More: 0.94
configure_requires:
  Devel::PPPort: 3.19
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.00'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Geo-Hash-XS
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  XSLoader: 0.1
resources:
  license: http://dev.perl.org/licenses/
version: 0.00012
